# Generated by Django 5.2 on 2025-04-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_number',
            field=models.CharField(max_length=50),
        ),
        # Commented out to avoid KeyError since the Slot model is already missing
        # migrations.DeleteModel(
        #     name='Slot',
        # ),
    ]
