# Generated by Django 5.2 on 2025-04-27 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkingslot_slot_number_delete_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='sub_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_slots', to='parking.subarea'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
