# Generated by Django 5.2 on 2025-04-27 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_area_description_subarea_description_alter_area_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='area',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='sub_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.subarea'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='parking.area'),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
