# Generated by Django 5.2 on 2025-04-27 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkingslot_area_alter_parkingslot_slot_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='sub_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkingslots', to='parking.subarea'),
        ),
    ]
