# Generated by Django 5.2 on 2025-04-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_parkingslot_sub_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='area',
        ),
    ]
