# Generated by Django 5.2 on 2025-04-27 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_loginregisterlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginregisterlog',
            name='event_type',
        ),
        migrations.AddField(
            model_name='loginregisterlog',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
