# Generated by Django 5.2 on 2025-05-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_remove_loginregisterlog_event_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginregisterlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Authentication Log', 'verbose_name_plural': 'User Authentication Logs'},
        ),
        migrations.AddField(
            model_name='loginregisterlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginregisterlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginregisterlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset')], max_length=50),
        ),
    ]
