# Generated by Django 5.2 on 2025-05-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_booking_actual_end_time_booking_actual_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='actual_end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='actual_start_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
