# Generated by Django 5.2 on 2025-05-07 15:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_remove_booking_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginregisterlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Login/Register Log', 'verbose_name_plural': 'Login/Register Logs'},
        ),
        migrations.AlterModelOptions(
            name='userauthenticationregistration',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Authentication Registration', 'verbose_name_plural': 'User Authentication Registrations'},
        ),
        migrations.RemoveField(
            model_name='loginregisterlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='loginregisterlog',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='loginregisterlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('logout', 'Logout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loginregisterlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginregisterlog',
            name='user',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to='auth.User',
                null=True,
                default=None
            ),
        ),
        migrations.AlterField(
            model_name='userauthenticationregistration',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('password_reset', 'Password Reset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userauthenticationregistration',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userauthenticationregistration',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userauthenticationregistration',
            name='user',
            field=models.ForeignKey(default='user@example.com', on_delete=django.db.models.deletion.CASCADE, related_name='auth_registrations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
