# Generated by Django 5.2 on 2025-05-07 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_alter_loginregisterlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginregisterlog',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
